<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../DesktopCalendarWidget/Models.cs" Link="Production/Models.cs" />
    <Compile Include="../../DesktopCalendarWidget/RestSchedule.cs" Link="Production/RestSchedule.cs" />
  </ItemGroup>
</Project>
